<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="Laraue.CmsBackend" Version="1.5.3"/>
        <PackageReference Include="SkiaSharp" Version="3.119.4" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="blog\**\*.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
